### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 

### ISSUE THREAD

**Issue by zhiweige** [leeesangwon/PyTorch-Image-Retrieval#10]
Thanks for your great  work on metric learning.
I have a question during I run the code.
I run the train code on cub200 data set, the script for the training is:
CUDA_VISIBLE_DEVICES='0' python main.py --model inceptionv3 --mode train --dataset-path ../../train_data/CUB_train_test/ --scheduler StepLR --input-size 299 --loss-type angular --model-save-dir ./models --num-classes 32

And I met the OOM error.
lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 492.88 MiB (GPU 0; 22.38 GiB total capacity; 13.54 GiB already allocated; 289.06 MiB free; 8.84 MiB cached)

Have you met this problem? 
Thanks.

**Comment by leeesangwon** [comment]
When we used 2 K80 GPUs for the training with an input size of 288, num-classes of 42 and densenet161, there was no out of memory error.
It might help to use smaller input_size, num_classes or base model.
Plus, because Angular loss only requires 2 samples per class for a batch sampler, you might save the memory for data loader by assigning the --num-samples 2 (current default is 4).

**Comment by zhiweige** [comment]
Thanks for your reply ^^ I used the inceptionv3 model when I tried to trian the network, maybe it caused the memory issue, I will change the parameters according to your suggestions .
