### ISSUE TITLE
How to use this code?

### ISSUE THREAD

**Issue by giangnguyen2412** [leeesangwon/PyTorch-Image-Retrieval#17]
Hi, I am just arriving here but after 30 mins going through this repo. I dont know how to run this repo.
Can you help me?

**Comment by Waverine** [comment]
I need some help, also...

**Comment by leeesangwon** [comment]
I'm sorry for the late reply and the lack of documentations.

For training or testing, you can start with `main.py`.
Please refer the arguments of the `main.py` below.

https://github.com/leeesangwon/PyTorch-Image-Retrieval/blob/b473b9fb7ab0e90838fecca03d8b4f58ede13049/main.py#L37-L65

You may also find the requirements to run this codes at the `setup.py`.
And you will need to modify `dataset.py` for your dataset.

Because our codes were influenced a lot by https://github.com/adambielski/siamese-triplet , I recommend you to refer to it.

**Comment by leeesangwon** [comment]
Closing the issue. Please reopen anytime if you need more help!
